//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatchMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public string user_id { get; set; }
        public string empl_num { get; set; }
        public string title_code { get; set; }
        public string fam_name { get; set; }
        public string given_name { get; set; }
        public string common_name { get; set; }
        public string gender { get; set; }
        public Nullable<int> position_code { get; set; }
        public string position_title { get; set; }
        public string bu_code { get; set; }
        public string bu_name { get; set; }
        public string tel_num { get; set; }
        public string is_active { get; set; }
        public string team { get; set; }
    }
}
