//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatchMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class information
    {
        public int information_id { get; set; }
        public int project_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<int> importance { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public int updated_by { get; set; }
        public Nullable<System.DateTime> updated_on { get; set; }
        public int state { get; set; }
    
        public virtual project project { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
