//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatchMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public int notification_id { get; set; }
        public int task_id { get; set; }
        public int sender_id { get; set; }
        public string sender_name { get; set; }
        public string recipients { get; set; }
        public Nullable<System.DateTime> sent_on { get; set; }
        public string recipients_id { get; set; }
        public Nullable<int> send_to_id { get; set; }
        public string comment { get; set; }
    
        public virtual task task { get; set; }
    }
}
