//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatchMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public project()
        {
            this.users = new HashSet<user>();
            this.tasks = new HashSet<task>();
        }
    
        public int project_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public bool is_active { get; set; }
    
        public virtual ICollection<user> users { get; set; }
        public virtual ICollection<task> tasks { get; set; }
    }
}
