//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatchMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewStatus
    {
        public int project_id { get; set; }
        public int user_id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public Nullable<int> newtask { get; set; }
        public Nullable<int> action { get; set; }
        public Nullable<int> investigation { get; set; }
        public Nullable<int> completed { get; set; }
        public Nullable<int> onhold { get; set; }
        public Nullable<int> problem { get; set; }
        public Nullable<int> no_issue { get; set; }
        public Nullable<int> passed { get; set; }
        public Nullable<int> failed { get; set; }
        public Nullable<int> total_open { get; set; }
        public Nullable<int> closed { get; set; }
        public Nullable<int> total { get; set; }
    }
}
