//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatchMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewTasks
    {
        public int project_id { get; set; }
        public int task_id { get; set; }
        public string initiator { get; set; }
        public Nullable<int> complexity_code { get; set; }
        public string complexity { get; set; }
        public Nullable<int> type_code { get; set; }
        public string type { get; set; }
        public Nullable<int> status_code { get; set; }
        public string status { get; set; }
        public Nullable<int> priority_code { get; set; }
        public string priority { get; set; }
        public string created_by { get; set; }
        public string creator_fn { get; set; }
        public string creator_ln { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string assigned_to { get; set; }
        public string assignee_fn { get; set; }
        public string assignee_ln { get; set; }
        public Nullable<System.DateTime> updated_on { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
    }
}
