//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatchMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewHistory
    {
        public int log_id { get; set; }
        public int user_id { get; set; }
        public string username { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public int task_id { get; set; }
        public string operation { get; set; }
        public string type { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> logtime { get; set; }
        public string old_val { get; set; }
        public string new_val { get; set; }
        public int StatusChange { get; set; }
        public string fname_new { get; set; }
        public string lname_new { get; set; }
    }
}
